### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by benoitbryon** [python-hospital/django-doctor#5]
Hi @jonklo,

What is the status of django-doctor and this repository? Would you accept pull-requests? May I update #4 and submit additional ones?

I may have an opportunity to work on some django app that integrates [hospital](http://hospital.readthedocs.org/).
My deadline is october 17th 2015 a.k.a. [PyCon FR 2015](http://www.pycon.fr/2015/), where I submitted a talk about hospital.

I'd prefer contribute to an existing project than creating yet another one...

**Comment by jonklo** [comment]
Hello, glad to hear that you have some time contributing! We could move this repo over to the hospital organization, so you’ll be free to commit directly to the repo.

Internally we only need something lightweight, really just the information from the “Technical Information” page. We might create a project just for that, so that django-doctor can be expanded with proper health checks. That makes sense for the name of the project as well :)

**Comment by benoitbryon** [comment]
> We could move this repo over to the hospital organization, so you’ll be free to commit directly to the repo.

You are in the list of owners of python-hospital organization: https://github.com/orgs/python-hospital/teams/owners ;)
Feel free to remove the fork and transfer ownership!
Of course I will continue to file pull-requests, so that you have the opportunity to review the changes :)

**Comment by benoitbryon** [comment]
> Internally we only need something lightweight, really just the information from the “Technical Information” page. We might create a project just for that, ...

Let's discuss it in depth in some ticket or pull-request ;)

**Comment by benoitbryon** [comment]
Thank you very much @jonklo :)
Just saw the move from funkbit to python-hospital, so I guess I can close this ticket...
